### ISSUE TITLE
Read Some good coding styles

### ISSUE THREAD

**Issue by sinhaaman** [emmcold/KoochiProblems#11]
http://www.inf.unibz.it/~nutt/Teaching/DSA1617/DSAAssignments/good-coding-style.html

**Comment by emmcold** [comment]
How did you get access to Nutt's material?

**Comment by sinhaaman** [comment]
On werner nutt website http://www.inf.unibz.it/~nutt/

**Comment by sinhaaman** [comment]
Did you complete this one?

**Comment by emmcold** [comment]
Yes, I did. :)
