### ISSUE TITLE
Linked List Problems which are written on Package.info and Launcher.java

### ISSUE THREAD

**Issue by sinhaaman** [emmcold/KoochiProblems#5]

**Comment by emmcold** [comment]
I just read what are XOR linked lists. Are doubly linked lists where you don't save both the pointers but you save in the XOR principle. Is this enough?

**Comment by emmcold** [comment]
I removed all the problems into package-info.

**Comment by emmcold** [comment]
Need to do these problems:

- [ ] Read problem 42 from the book of Karumanchi pdf 
- [ ] Read & Solve problem 44 from the book 
- [ ] Read the question about ordering the linked list (Snake solution)
- [ ] Read Question 51 from the book of Karumanchi pdf

**Comment by emmcold** [comment]
Here you go! BYE@
